//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesHub_WinForm.NotesHubService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/NotesHub_Service")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> created_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> last_viewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> created_at {
            get {
                return this.created_atField;
            }
            set {
                if ((this.created_atField.Equals(value) != true)) {
                    this.created_atField = value;
                    this.RaisePropertyChanged("created_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> last_viewed {
            get {
                return this.last_viewedField;
            }
            set {
                if ((this.last_viewedField.Equals(value) != true)) {
                    this.last_viewedField = value;
                    this.RaisePropertyChanged("last_viewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupModel", Namespace="http://schemas.datacontract.org/2004/07/NotesHub_Service")]
    [System.SerializableAttribute()]
    public partial class GroupModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> created_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> created_at {
            get {
                return this.created_atField;
            }
            set {
                if ((this.created_atField.Equals(value) != true)) {
                    this.created_atField = value;
                    this.RaisePropertyChanged("created_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupUserModel", Namespace="http://schemas.datacontract.org/2004/07/NotesHub_Service")]
    [System.SerializableAttribute()]
    public partial class GroupUserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> group_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> group_id {
            get {
                return this.group_idField;
            }
            set {
                if ((this.group_idField.Equals(value) != true)) {
                    this.group_idField = value;
                    this.RaisePropertyChanged("group_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostModel", Namespace="http://schemas.datacontract.org/2004/07/NotesHub_Service")]
    [System.SerializableAttribute()]
    public partial class PostModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotesHub_WinForm.NotesHubService.DocumentModel[] DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> created_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> group_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotesHub_WinForm.NotesHubService.DocumentModel[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> created_at {
            get {
                return this.created_atField;
            }
            set {
                if ((this.created_atField.Equals(value) != true)) {
                    this.created_atField = value;
                    this.RaisePropertyChanged("created_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> group_id {
            get {
                return this.group_idField;
            }
            set {
                if ((this.group_idField.Equals(value) != true)) {
                    this.group_idField = value;
                    this.RaisePropertyChanged("group_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentModel", Namespace="http://schemas.datacontract.org/2004/07/NotesHub_Service")]
    [System.SerializableAttribute()]
    public partial class DocumentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fileBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] fileBytes {
            get {
                return this.fileBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.fileBytesField, value) != true)) {
                    this.fileBytesField = value;
                    this.RaisePropertyChanged("fileBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotesHubService.INotesHubService")]
    public interface INotesHubService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetUserById", ReplyAction="http://tempuri.org/INotesHubService/GetUserByIdResponse")]
        NotesHub_WinForm.NotesHubService.UserModel GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetUserById", ReplyAction="http://tempuri.org/INotesHubService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.UserModel> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/Signup", ReplyAction="http://tempuri.org/INotesHubService/SignupResponse")]
        int Signup(NotesHub_WinForm.NotesHubService.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/Signup", ReplyAction="http://tempuri.org/INotesHubService/SignupResponse")]
        System.Threading.Tasks.Task<int> SignupAsync(NotesHub_WinForm.NotesHubService.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/Login", ReplyAction="http://tempuri.org/INotesHubService/LoginResponse")]
        int Login(NotesHub_WinForm.NotesHubService.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/Login", ReplyAction="http://tempuri.org/INotesHubService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(NotesHub_WinForm.NotesHubService.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetGroupById", ReplyAction="http://tempuri.org/INotesHubService/GetGroupByIdResponse")]
        NotesHub_WinForm.NotesHubService.GroupModel GetGroupById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetGroupById", ReplyAction="http://tempuri.org/INotesHubService/GetGroupByIdResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.GroupModel> GetGroupByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllGroup", ReplyAction="http://tempuri.org/INotesHubService/GetAllGroupResponse")]
        NotesHub_WinForm.NotesHubService.GroupModel[] GetAllGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllGroup", ReplyAction="http://tempuri.org/INotesHubService/GetAllGroupResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.GroupModel[]> GetAllGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/CreateGroup", ReplyAction="http://tempuri.org/INotesHubService/CreateGroupResponse")]
        int CreateGroup(NotesHub_WinForm.NotesHubService.GroupModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/CreateGroup", ReplyAction="http://tempuri.org/INotesHubService/CreateGroupResponse")]
        System.Threading.Tasks.Task<int> CreateGroupAsync(NotesHub_WinForm.NotesHubService.GroupModel group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/JoinGroup", ReplyAction="http://tempuri.org/INotesHubService/JoinGroupResponse")]
        int JoinGroup(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/JoinGroup", ReplyAction="http://tempuri.org/INotesHubService/JoinGroupResponse")]
        System.Threading.Tasks.Task<int> JoinGroupAsync(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/LeaveGroup", ReplyAction="http://tempuri.org/INotesHubService/LeaveGroupResponse")]
        bool LeaveGroup(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/LeaveGroup", ReplyAction="http://tempuri.org/INotesHubService/LeaveGroupResponse")]
        System.Threading.Tasks.Task<bool> LeaveGroupAsync(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllGroupUsers", ReplyAction="http://tempuri.org/INotesHubService/GetAllGroupUsersResponse")]
        NotesHub_WinForm.NotesHubService.UserModel[] GetAllGroupUsers(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllGroupUsers", ReplyAction="http://tempuri.org/INotesHubService/GetAllGroupUsersResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.UserModel[]> GetAllGroupUsersAsync(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllGroupByUserId", ReplyAction="http://tempuri.org/INotesHubService/GetAllGroupByUserIdResponse")]
        NotesHub_WinForm.NotesHubService.GroupModel[] GetAllGroupByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllGroupByUserId", ReplyAction="http://tempuri.org/INotesHubService/GetAllGroupByUserIdResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.GroupModel[]> GetAllGroupByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetPostById", ReplyAction="http://tempuri.org/INotesHubService/GetPostByIdResponse")]
        NotesHub_WinForm.NotesHubService.PostModel GetPostById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetPostById", ReplyAction="http://tempuri.org/INotesHubService/GetPostByIdResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel> GetPostByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/CreatePost", ReplyAction="http://tempuri.org/INotesHubService/CreatePostResponse")]
        int CreatePost(NotesHub_WinForm.NotesHubService.PostModel post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/CreatePost", ReplyAction="http://tempuri.org/INotesHubService/CreatePostResponse")]
        System.Threading.Tasks.Task<int> CreatePostAsync(NotesHub_WinForm.NotesHubService.PostModel post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/DeletePost", ReplyAction="http://tempuri.org/INotesHubService/DeletePostResponse")]
        bool DeletePost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/DeletePost", ReplyAction="http://tempuri.org/INotesHubService/DeletePostResponse")]
        System.Threading.Tasks.Task<bool> DeletePostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllPost", ReplyAction="http://tempuri.org/INotesHubService/GetAllPostResponse")]
        NotesHub_WinForm.NotesHubService.PostModel[] GetAllPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllPost", ReplyAction="http://tempuri.org/INotesHubService/GetAllPostResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel[]> GetAllPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllPostByGroupId", ReplyAction="http://tempuri.org/INotesHubService/GetAllPostByGroupIdResponse")]
        NotesHub_WinForm.NotesHubService.PostModel[] GetAllPostByGroupId(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllPostByGroupId", ReplyAction="http://tempuri.org/INotesHubService/GetAllPostByGroupIdResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel[]> GetAllPostByGroupIdAsync(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllPostByUserId", ReplyAction="http://tempuri.org/INotesHubService/GetAllPostByUserIdResponse")]
        NotesHub_WinForm.NotesHubService.PostModel[] GetAllPostByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotesHubService/GetAllPostByUserId", ReplyAction="http://tempuri.org/INotesHubService/GetAllPostByUserIdResponse")]
        System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel[]> GetAllPostByUserIdAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotesHubServiceChannel : NotesHub_WinForm.NotesHubService.INotesHubService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotesHubServiceClient : System.ServiceModel.ClientBase<NotesHub_WinForm.NotesHubService.INotesHubService>, NotesHub_WinForm.NotesHubService.INotesHubService {
        
        public NotesHubServiceClient() {
        }
        
        public NotesHubServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotesHubServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotesHubServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotesHubServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NotesHub_WinForm.NotesHubService.UserModel GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.UserModel> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public int Signup(NotesHub_WinForm.NotesHubService.UserModel user) {
            return base.Channel.Signup(user);
        }
        
        public System.Threading.Tasks.Task<int> SignupAsync(NotesHub_WinForm.NotesHubService.UserModel user) {
            return base.Channel.SignupAsync(user);
        }
        
        public int Login(NotesHub_WinForm.NotesHubService.UserModel user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(NotesHub_WinForm.NotesHubService.UserModel user) {
            return base.Channel.LoginAsync(user);
        }
        
        public NotesHub_WinForm.NotesHubService.GroupModel GetGroupById(int id) {
            return base.Channel.GetGroupById(id);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.GroupModel> GetGroupByIdAsync(int id) {
            return base.Channel.GetGroupByIdAsync(id);
        }
        
        public NotesHub_WinForm.NotesHubService.GroupModel[] GetAllGroup() {
            return base.Channel.GetAllGroup();
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.GroupModel[]> GetAllGroupAsync() {
            return base.Channel.GetAllGroupAsync();
        }
        
        public int CreateGroup(NotesHub_WinForm.NotesHubService.GroupModel group) {
            return base.Channel.CreateGroup(group);
        }
        
        public System.Threading.Tasks.Task<int> CreateGroupAsync(NotesHub_WinForm.NotesHubService.GroupModel group) {
            return base.Channel.CreateGroupAsync(group);
        }
        
        public int JoinGroup(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser) {
            return base.Channel.JoinGroup(groupUser);
        }
        
        public System.Threading.Tasks.Task<int> JoinGroupAsync(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser) {
            return base.Channel.JoinGroupAsync(groupUser);
        }
        
        public bool LeaveGroup(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser) {
            return base.Channel.LeaveGroup(groupUser);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveGroupAsync(NotesHub_WinForm.NotesHubService.GroupUserModel groupUser) {
            return base.Channel.LeaveGroupAsync(groupUser);
        }
        
        public NotesHub_WinForm.NotesHubService.UserModel[] GetAllGroupUsers(int groupId) {
            return base.Channel.GetAllGroupUsers(groupId);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.UserModel[]> GetAllGroupUsersAsync(int groupId) {
            return base.Channel.GetAllGroupUsersAsync(groupId);
        }
        
        public NotesHub_WinForm.NotesHubService.GroupModel[] GetAllGroupByUserId(int userId) {
            return base.Channel.GetAllGroupByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.GroupModel[]> GetAllGroupByUserIdAsync(int userId) {
            return base.Channel.GetAllGroupByUserIdAsync(userId);
        }
        
        public NotesHub_WinForm.NotesHubService.PostModel GetPostById(int id) {
            return base.Channel.GetPostById(id);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel> GetPostByIdAsync(int id) {
            return base.Channel.GetPostByIdAsync(id);
        }
        
        public int CreatePost(NotesHub_WinForm.NotesHubService.PostModel post) {
            return base.Channel.CreatePost(post);
        }
        
        public System.Threading.Tasks.Task<int> CreatePostAsync(NotesHub_WinForm.NotesHubService.PostModel post) {
            return base.Channel.CreatePostAsync(post);
        }
        
        public bool DeletePost(int id) {
            return base.Channel.DeletePost(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePostAsync(int id) {
            return base.Channel.DeletePostAsync(id);
        }
        
        public NotesHub_WinForm.NotesHubService.PostModel[] GetAllPost() {
            return base.Channel.GetAllPost();
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel[]> GetAllPostAsync() {
            return base.Channel.GetAllPostAsync();
        }
        
        public NotesHub_WinForm.NotesHubService.PostModel[] GetAllPostByGroupId(int groupId) {
            return base.Channel.GetAllPostByGroupId(groupId);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel[]> GetAllPostByGroupIdAsync(int groupId) {
            return base.Channel.GetAllPostByGroupIdAsync(groupId);
        }
        
        public NotesHub_WinForm.NotesHubService.PostModel[] GetAllPostByUserId(int userId) {
            return base.Channel.GetAllPostByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<NotesHub_WinForm.NotesHubService.PostModel[]> GetAllPostByUserIdAsync(int userId) {
            return base.Channel.GetAllPostByUserIdAsync(userId);
        }
    }
}
